name: Deploy

on:
  release:
    types: [published]

defaults:
  run:
    shell: bash

jobs:
  pre-deploy-checks:
    name: Deploy to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
        with:
          python-version: "3.11"
          venv-id: "deploy"
          poetry-dependency-install-flags: "--all-extras"
      - name: Run tests
        run: |
          poetry run pytest -r a src tests --doctest-modules

  upload-all:
    name: Upload if release
    needs: [ build_wheels, build_sdist, pre-deploy-checks ]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    environment: pypi
    permissions:
      id-token: write

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - uses: actions/download-artifact@v4
        with:
          pattern: cibw-*
          merge-multiple: true
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1
